// Buffer (social scheduling) GraphQL client. All Buffer API specifics live HERE so the routes/UI
// consume a stable, normalized shape — any schema tweaks after introspection stay localized.
// API: https://api.buffer.com (GraphQL), Bearer token (BUFFER_API_TOKEN, account-wide).
const BUFFER_API = "https://api.buffer.com"

export type BufferChannel = { id: string; name: string; service: string; avatar?: string | null }
export type BufferDraft = {
  id: string
  text: string
  status: string
  createdAt?: string | null
  dueAt?: string | null
  channel: BufferChannel | null
  media: string[] // image/video preview URLs (best-effort)
}
export type ApproveMode = "queue" | "schedule" | "now"

export class BufferError extends Error {}

function token(): string {
  const t = process.env.BUFFER_API_TOKEN
  if (!t) throw new BufferError("BUFFER_API_TOKEN belum diset di server.")
  return t
}

// Images generated by the automation now live under NEXUS's stable file server. Old drafts still
// reference a dead trycloudflare tunnel URL in Buffer — but the FILE exists locally, so we re-point
// the URL (same filename) to the stable NEXUS host. Used both for read-preview and on approve.
const NEXUS_IMG_BASE = "https://nexus.patsgroup.id/api/files/attachments/social-buffer/centipede-exports/"
function stableUrl(src: string | null | undefined): string {
  const s = src || ""
  if (s.includes("trycloudflare")) return NEXUS_IMG_BASE + (s.split("/").pop() || "")
  return s
}

async function gql<T = any>(query: string, variables?: Record<string, unknown>): Promise<T> {
  const res = await fetch(BUFFER_API, {
    method: "POST",
    headers: { "Content-Type": "application/json", Authorization: `Bearer ${token()}` },
    body: JSON.stringify({ query, variables: variables ?? {} }),
    signal: AbortSignal.timeout(20000),
  })
  const json = await res.json().catch(() => null)
  if (!res.ok) throw new BufferError(`Buffer API HTTP ${res.status}`)
  if (json?.errors?.length) throw new BufferError(json.errors.map((e: { message?: string }) => e?.message).filter(Boolean).join("; ") || "Buffer GraphQL error")
  return json?.data as T
}

// Buffer's mutations return a union: PostActionSuccess { post } | MutationError { message }.
function unwrapPostAction(payload: { post?: { id?: string }; message?: string } | null, op: string): { id?: string } {
  if (!payload) throw new BufferError(`${op}: respons kosong dari Buffer.`)
  if (payload.message) throw new BufferError(`${op}: ${payload.message}`)
  return payload.post ?? {}
}

let cachedOrgId: string | null = null
async function organizationId(): Promise<string> {
  if (cachedOrgId) return cachedOrgId
  const data = await gql<{ account?: { organizations?: { id: string }[] } }>(
    `query { account { id organizations { id name } } }`,
  )
  const org = data?.account?.organizations?.[0]
  if (!org?.id) throw new BufferError("Gak nemu organization di akun Buffer ini.")
  cachedOrgId = org.id
  return org.id
}

export async function listChannels(): Promise<BufferChannel[]> {
  const orgId = await organizationId()
  const data = await gql<{ channels?: BufferChannel[] }>(
    `query Channels($orgId: OrganizationId!) { channels(input: { organizationId: $orgId }) { id name service avatar } }`,
    { orgId },
  )
  return data?.channels ?? []
}

// Raw editable fields needed to re-send on approve (editPost on Instagram REPLACES, not merges).
// listDrafts already pulls these, so we stash them keyed by id — approveDraft reuses them instead of
// issuing a second `fetchDraft` query, halving the Buffer call count per approval (2 → 1).
type DraftEditable = {
  text?: string
  metadata?: { __typename?: string; type?: string; shouldShareToFeed?: boolean } | null
  assets?: { type?: string; source?: string; thumbnail?: string }[]
}
let draftEditableById = new Map<string, DraftEditable>()

// Drafts awaiting approval (status: draft), with media preview (Asset.thumbnail/source) and the
// editable fields (text/metadata/assets) cached for approve to reuse.
export async function listDrafts(): Promise<BufferDraft[]> {
  const orgId = await organizationId()
  const data = await gql<{ posts?: { edges?: { node: any }[] } }>(
    `query Drafts($orgId: OrganizationId!) {
      posts(first: 50, input: { organizationId: $orgId, filter: { status: [draft] } }) {
        edges { node {
          id text status dueAt createdAt
          channel { id name service avatar }
          metadata { __typename ... on InstagramPostMetadata { type shouldShareToFeed } }
          assets { type source thumbnail }
        } }
      }
    }`,
    { orgId },
  )
  const edges = data?.posts?.edges ?? []
  // Rebuild the editable map from scratch so it always mirrors the latest list (bounded, self-pruning).
  const nextEditable = new Map<string, DraftEditable>()
  const drafts = edges.map((e) => {
    const n = e.node
    nextEditable.set(n.id, { text: n.text ?? "", metadata: n.metadata ?? null, assets: n.assets ?? [] })
    const media = (n.assets ?? [])
      .map((a: { thumbnail?: string; source?: string }) => stableUrl(a?.thumbnail || a?.source))
      .filter((u: unknown): u is string => typeof u === "string" && u.length > 0)
    return {
      id: n.id,
      text: n.text ?? "",
      status: n.status ?? "draft",
      createdAt: n.createdAt ?? null,
      dueAt: n.dueAt ?? null,
      channel: n.channel ? { id: n.channel.id, name: n.channel.name, service: n.channel.service, avatar: n.channel.avatar } : null,
      media,
    }
  })
  draftEditableById = nextEditable
  return drafts
}

// --- Drafts cache -----------------------------------------------------------------------------
// Buffer is hard-capped at 250 calls / 24h (and 100 / 15min). The approvals board is polled and can
// be open in several tabs, so we coalesce reads through a tiny module-level cache. Mutations bust it
// so approve/reject reflect immediately. peek() lets the route serve the last good list on a 429.
type DraftsCache = { at: number; drafts: BufferDraft[] }
let draftsCache: DraftsCache | null = null

export async function listDraftsCached(ttlMs: number): Promise<{ drafts: BufferDraft[]; cached: boolean }> {
  const now = Date.now()
  if (draftsCache && now - draftsCache.at < ttlMs) return { drafts: draftsCache.drafts, cached: true }
  const drafts = await listDrafts()
  draftsCache = { at: now, drafts }
  return { drafts, cached: false }
}

// Last good draft list (any age) — used to keep the board populated when a refresh hits a rate limit.
export function peekDraftsCache(): BufferDraft[] | null {
  return draftsCache?.drafts ?? null
}

// Invalidate after any mutation so the next read is fresh (the approved/rejected draft is gone).
export function bustDraftsCache(): void {
  draftsCache = null
}

// Fetch a draft's editable fields. editPost on Instagram REPLACES (not merges), and requires
// metadata.instagram.{type, shouldShareToFeed} + assets — so we must re-send them to preserve.
async function fetchDraft(postId: string) {
  const orgId = await organizationId()
  const data = await gql<{ posts?: { edges?: { node: any }[] } }>(
    `query Draft($o: OrganizationId!) {
      posts(first: 100, input: { organizationId: $o, filter: { status: [draft] } }) {
        edges { node {
          id text
          metadata { __typename ... on InstagramPostMetadata { type shouldShareToFeed firstComment link } }
          assets { type source thumbnail }
        } }
      }
    }`,
    { o: orgId },
  )
  const node = (data?.posts?.edges ?? []).map((e) => e.node).find((n) => n.id === postId)
  if (!node) throw new BufferError("Draft gak ketemu di Buffer (mungkin udah diproses).")
  return node
}

// Approve a draft = editPost(saveToDraft:false). queue → addToQueue (Buffer schedules per channel
// schedule), schedule → customScheduled + dueAt, now → shareNow. We preserve text + image + required
// Instagram metadata, and re-point any dead tunnel image URL to the stable NEXUS host.
export async function approveDraft(postId: string, mode: ApproveMode, dueAt?: string): Promise<{ id?: string }> {
  const shareMode = mode === "queue" ? "addToQueue" : mode === "now" ? "shareNow" : "customScheduled"
  if (mode === "schedule" && !dueAt) throw new BufferError("Tanggal/jam tayang wajib diisi buat 'Jadwalin'.")
  // Reuse the editable detail captured by the last listDrafts (board was just rendered from it) to skip
  // a redundant Buffer call. Fall back to a fresh fetch only if the cache is cold (e.g. server restart).
  const d = draftEditableById.get(postId) ?? (await fetchDraft(postId))
  const assets = (d.assets ?? [])
    .filter((a: { source?: string }) => a?.source)
    .map((a: { source: string; thumbnail?: string }) => ({ image: { url: stableUrl(a.source), thumbnailUrl: stableUrl(a.thumbnail || a.source) } }))
  const input: Record<string, unknown> = {
    id: postId, schedulingType: "automatic", mode: shareMode, saveToDraft: false, text: d.text ?? "", assets,
  }
  if (mode === "schedule") input.dueAt = dueAt
  if (d.metadata?.__typename === "InstagramPostMetadata") {
    input.metadata = { instagram: { type: d.metadata.type || "post", shouldShareToFeed: d.metadata.shouldShareToFeed ?? true } }
  }
  const data = await gql<{ editPost?: { post?: { id: string }; message?: string } }>(
    `mutation Approve($input: EditPostInput!) {
      editPost(input: $input) {
        ... on PostActionSuccess { post { id status dueAt } }
        ... on MutationError { message }
      }
    }`,
    { input },
  )
  const out = unwrapPostAction(data?.editPost ?? null, "Approve")
  bustDraftsCache() // the draft left the queue → next read must be fresh
  return out
}

// Reject = deletePost. NOTE: deletePost returns DeletePostPayload = DeletePostSuccess | VoidMutationError
// (a DIFFERENT union from edit/create), so the fragments differ.
export async function rejectDraft(postId: string): Promise<{ id?: string }> {
  const data = await gql<{ deletePost?: { id?: string; message?: string } }>(
    `mutation Reject($input: DeletePostInput!) {
      deletePost(input: $input) {
        ... on DeletePostSuccess { id }
        ... on VoidMutationError { message }
      }
    }`,
    { input: { id: postId } },
  )
  const dp = data?.deletePost
  if (!dp) throw new BufferError("Reject: respons kosong dari Buffer.")
  if (dp.message) throw new BufferError(`Reject: ${dp.message}`)
  bustDraftsCache() // the draft is gone → next read must be fresh
  return { id: dp.id }
}

export function bufferConfigured(): boolean {
  return !!process.env.BUFFER_API_TOKEN
}
