services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:3000"
    environment:
      # GANTI 192.168.1.100 dengan IP NAS Synology kamu
      DATABASE_URL: "postgresql://nexus_user:password123@192.168.1.100:5432/nexus_db?schema=public"
      AUTH_SECRET: "83917d299c83455a82d226f4a0f3b0f677e3a8abf210d297baae0d95d4ddd0a0"
      NEXTAUTH_URL: "http://localhost:3000" # Nanti ganti ke domain publik (misal https://nexus.kamu.com)
      NEXTAUTH_SECRET: "83917d299c83455a82d226f4a0f3b0f677e3a8abf210d297baae0d95d4ddd0a0"
    # Kita tidak butuh 'depends_on' karena database ada di luar Mac ini (di NAS)
