/**
 * Emits idempotent SQL that sets up the Legal project's document-request intake:
 *   - one custom field per template slot (LEGAL_FIELDS — the single source of truth)
 *   - two forms: "Pengajuan Invoice" and "Pengajuan Kontrak / PKS", each mapping its inputs into
 *     those custom fields
 *
 * Prints to stdout; apply with psql. Safe to re-run — every statement is guarded by NOT EXISTS, so it
 * adds only what's missing and never rewrites a field someone has since edited in the UI.
 *
 *   npx tsx scripts/legal-forms-sql.ts > /tmp/legal-forms.sql
 *   docker exec -i nexus-postgres psql -U nexus_user -d nexus_db -v ON_ERROR_STOP=1 < /tmp/legal-forms.sql
 */
import {
  LEGAL_FIELDS, activeLegalFields, formFieldsFor, docTypeLabelsFor, DOC_TYPE_OPTIONS, ACTIVE_DOC_KINDS,
  type DocKind, type LegalFieldKey,
} from "../src/lib/legal-templates/fields"

const PROJECT_ID = "cmnzxtetd005y01qhdwpmkar6" // Legal
/**
 * Each document type has its OWN intake section on the Legal board, so a form has a fixed destination
 * and the requester is never asked to route their own request.
 *
 * This replaced a "Unit" dropdown mapped to `task_list`: the public form route auto-syncs any
 * task_list dropdown to the project's CURRENT section names, which dragged "In Progress" and "Done"
 * into the requester's list — meaning a request could land straight in the Done column and never be
 * seen. Routing now happens through an explicit rule on the (always-filled) title field.
 */
const INTAKE_SECTION: Record<DocKind, string> = {
  INVOICE: "legalsec_invoice",   // "Invoice Talent PATS Entertainment"
  MOU: "legalsec_mou",           // "MOU Talent PATS Entertainment"
  CONTRACT: "legalsec_invoice",  // retired; only used if CONTRACT is re-activated
}

const q = (s: string) => `'${s.replace(/'/g, "''")}'`
const qj = (v: unknown) => q(JSON.stringify(v))
/** Deterministic ids so re-running references the same rows instead of duplicating them. */
const cfId = (key: LegalFieldKey) => `legalcf_${key}`
const formId = (kind: string) => `legalform_${kind.toLowerCase()}`

const out: string[] = [
  "-- Legal document-request intake: custom fields + two forms.",
  "-- Generated by scripts/legal-forms-sql.ts — edit LEGAL_FIELDS, not this file.",
  "BEGIN;",
  "",
  "-- 1. Custom fields = the template slots. Guarded by name+type so a field the team already made by",
  "--    hand is reused rather than duplicated.",
]

// Existing "Status" field sits at position 0; append after it.
let pos = 1
for (const f of activeLegalFields()) {
  out.push(
    `INSERT INTO "CustomField" ("id", "name", "type", "options", "position", "projectId")`,
    `SELECT ${q(cfId(f.key))}, ${q(f.name)}, ${q(f.type)}::"CustomFieldType", ${f.options ? `${qj(f.options)}::jsonb` : "NULL"}, ${pos}, ${q(PROJECT_ID)}`,
    `WHERE NOT EXISTS (SELECT 1 FROM "CustomField" c WHERE c."projectId" = ${q(PROJECT_ID)}`,
    `  AND lower(btrim(c."name")) = lower(btrim(${q(f.name)})) AND c."type" = ${q(f.type)}::"CustomFieldType");`,
    "",
  )
  pos += 1
}

/**
 * Build a form's `fields` JSON in the shape the existing Pengajuan Finance forms use: every input
 * carries a `mapping` telling the submit route where the answer goes.
 */
function buildForm(kind: DocKind) {
  const fields: Record<string, unknown>[] = [
    // Title + description are what show on the board card, so they're asked first.
    {
      id: "f_title", name: "Pengajuan Apa?", label: "Pengajuan Apa?", type: "text", required: true,
      mapping: { target: "task_title" },
      // The title is required, so this rule always fires — it's how the form pins its own destination
      // section without asking the requester anything.
      routingRules: [{
        operator: "is_not_empty", value: "",
        action: "set_task_list", targetTaskListId: INTAKE_SECTION[kind],
      }],
      placeholder: kind === "INVOICE" ? "mis. Invoice talent XORA - Goedang Banjarmasin"
        : kind === "MOU" ? "mis. MOU Event SOUTHBOUND - XORA"
        : "mis. Kontrak PKS Johnnie Walker - Omnicom",
    },
    {
      id: "f_notes", name: "Catatan Tambahan", label: "Catatan Tambahan", type: "textarea", required: false,
      mapping: { target: "task_description" }, routingRules: [],
      help: "Hal-hal yang nggak ketampung di field lain.",
    },
  ]

  for (const f of formFieldsFor(kind)) {
    // Per-form doc type: offer only this form's own kind (see docTypeLabelsFor).
    const options = f.key === "docType" ? docTypeLabelsFor(kind) : f.options
    fields.push({
      id: `f_${f.key}`,
      name: f.name,
      label: f.name,
      type: f.input,
      required: f.required,
      ...(options ? { options } : {}),
      ...(f.help ? { help: f.help } : {}),
      mapping: { target: "custom_field", customFieldId: cfId(f.key) },
      routingRules: [],
    })
  }
  return fields
}

const ALL_FORMS = [
  {
    kind: "INVOICE" as const,
    id: formId("invoice"),
    slug: "pengajuan-invoice-talent-pats-entertainment",
    name: "Pengajuan Invoice Talent PATS Entertainment",
    description:
      "Isi bagian pentingnya aja — nomor invoice dan terbilang digenerate otomatis, sisanya udah template.",
  },
  {
    kind: "CONTRACT" as const,
    id: formId("kontrak"),
    slug: "pengajuan-kontrak-pks-jagain",
    name: "Pengajuan Kontrak / PKS",
    description:
      "Isi data klien dan nilai kerja samanya — 12 pasal, nomor PKS, dan terbilang digenerate otomatis.",
  },
  {
    kind: "MOU" as const,
    id: formId("mou"),
    slug: "pengajuan-mou-event-talent",
    name: "Pengajuan MOU Event Talent",
    description:
      "MOU booking talent. Riders dan akomodasi diisi per deal (satu item per baris). MOU nggak pakai nomor dokumen.",
  },
]
const FORMS = ALL_FORMS.filter((f) => ACTIVE_DOC_KINDS.includes(f.kind))
const RETIRED_FORM_IDS = ALL_FORMS.filter((f) => !ACTIVE_DOC_KINDS.includes(f.kind)).map((f) => f.id)

out.push("-- 2. The two intake forms. requireAuth = the submitter is always recorded, so Legal knows who")
out.push("--    asked and the requester can track it under \"Pengajuan Saya\".", "")
for (const f of FORMS) {
  const fields = buildForm(f.kind)
  out.push(
    `INSERT INTO "Form" ("id", "name", "slug", "description", "fields", "isPublic", "requireAuth", "projectId", "createdAt", "updatedAt")`,
    `SELECT ${q(f.id)}, ${q(f.name)}, ${q(f.slug)}, ${q(f.description)}, ${qj(fields)}::jsonb, true, true, ${q(PROJECT_ID)}, NOW(), NOW()`,
    `WHERE NOT EXISTS (SELECT 1 FROM "Form" x WHERE x."id" = ${q(f.id)}`,
    `  OR (x."projectId" = ${q(PROJECT_ID)} AND x."name" = ${q(f.name)}));`,
    // Refresh OUR row's field set. Insert-only-if-missing would leave an earlier, wrong field set in
    // place forever; scoping the UPDATE to our deterministic id means a form the team built by hand
    // (different id, maybe same name) is never overwritten.
    `UPDATE "Form" SET "name" = ${q(f.name)}, "slug" = ${q(f.slug)}, "isPublic" = true, "fields" = ${qj(fields)}::jsonb, "description" = ${q(f.description)}, "updatedAt" = NOW()`,
    `  WHERE "id" = ${q(f.id)};`,
    "",
  )
}

// Cleanup: anything WE created that no active document kind needs any more. Scoped to our own
// deterministic ids and guarded on being unused, so nothing the team made or filled is ever dropped.
const keepIds = new Set(activeLegalFields().map((f) => cfId(f.key)))
const retiredFieldIds = LEGAL_FIELDS.map((f) => cfId(f.key)).filter((id) => !keepIds.has(id))

out.push(
  "-- 3. Retire what's no longer offered. Both deletes are scoped to ids this script created AND",
  "--    guarded on being unused, so a field someone already filled (or a form with submissions) stays.",
  ...(retiredFieldIds.length ? [
    `DELETE FROM "CustomField" AS c WHERE c."id" IN (${retiredFieldIds.map(q).join(", ")})`,
    `  AND NOT EXISTS (SELECT 1 FROM "CustomFieldValue" v WHERE v."customFieldId" = c."id");`,
  ] : []),
  ...(RETIRED_FORM_IDS.length ? [
    `DELETE FROM "Form" AS f WHERE f."id" IN (${RETIRED_FORM_IDS.map(q).join(", ")})`,
    `  AND NOT EXISTS (SELECT 1 FROM "FormSubmission" s WHERE s."formId" = f."id");`,
  ] : []),
  "",
  "COMMIT;",
  "",
  "-- Sanity check after applying:",
  `--   SELECT name, type FROM "CustomField" WHERE "projectId" = ${q(PROJECT_ID)} ORDER BY position;`,
  `--   SELECT name, jsonb_array_length(fields::jsonb) FROM "Form" WHERE "projectId" = ${q(PROJECT_ID)};`,
)

console.log(out.join("\n"))
console.error(
  `[legal-forms-sql] aktif: ${ACTIVE_DOC_KINDS.join("+")} | ${activeLegalFields().length}/${LEGAL_FIELDS.length} custom fields, ` +
  FORMS.map((f) => `${f.name}: ${buildForm(f.kind).length} fields`).join(", ") +
  `, doc types: ${DOC_TYPE_OPTIONS.length}, retired: ${retiredFieldIds.length} field + ${RETIRED_FORM_IDS.length} form`,
)
