/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as PhaethonRouteImport } from './routes/phaethon'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as OauthAuthorizeRouteImport } from './routes/oauth.authorize'
import { Route as FFormIdRouteImport } from './routes/f.$formId'
import { Route as AppTeamsRouteImport } from './routes/_app/teams'
import { Route as AppSubmissionsRouteImport } from './routes/_app/submissions'
import { Route as AppSocialRouteImport } from './routes/_app/social'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppRoomBookingRouteImport } from './routes/_app/room-booking'
import { Route as AppReportsRouteImport } from './routes/_app/reports'
import { Route as AppPeerReportsRouteImport } from './routes/_app/peer-reports'
import { Route as AppOracleRouteImport } from './routes/_app/oracle'
import { Route as AppMyTasksRouteImport } from './routes/_app/my-tasks'
import { Route as AppMessagesRouteImport } from './routes/_app/messages'
import { Route as AppMasterCalendarRouteImport } from './routes/_app/master-calendar'
import { Route as AppLeaderboardRouteImport } from './routes/_app/leaderboard'
import { Route as AppInboxRouteImport } from './routes/_app/inbox'
import { Route as AppFormsRouteImport } from './routes/_app/forms'
import { Route as AppFeedRouteImport } from './routes/_app/feed'
import { Route as AppDocsRouteImport } from './routes/_app/docs'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppAttendanceRouteImport } from './routes/_app/attendance'
import { Route as AppAdminRouteImport } from './routes/_app/admin'
import { Route as AppProjectsIndexRouteImport } from './routes/_app/projects/index'
import { Route as AppTasksTaskIdRouteImport } from './routes/_app/tasks.$taskId'
import { Route as AppProjectsProjectIdRouteImport } from './routes/_app/projects/$projectId'
import { Route as AppFoldersFolderIdRouteImport } from './routes/_app/folders.$folderId'
import { Route as AppDocsDocIdRouteImport } from './routes/_app/docs.$docId'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PhaethonRoute = PhaethonRouteImport.update({
  id: '/phaethon',
  path: '/phaethon',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const OauthAuthorizeRoute = OauthAuthorizeRouteImport.update({
  id: '/oauth/authorize',
  path: '/oauth/authorize',
  getParentRoute: () => rootRouteImport,
} as any)
const FFormIdRoute = FFormIdRouteImport.update({
  id: '/f/$formId',
  path: '/f/$formId',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTeamsRoute = AppTeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => AppRoute,
} as any)
const AppSubmissionsRoute = AppSubmissionsRouteImport.update({
  id: '/submissions',
  path: '/submissions',
  getParentRoute: () => AppRoute,
} as any)
const AppSocialRoute = AppSocialRouteImport.update({
  id: '/social',
  path: '/social',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppRoomBookingRoute = AppRoomBookingRouteImport.update({
  id: '/room-booking',
  path: '/room-booking',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppPeerReportsRoute = AppPeerReportsRouteImport.update({
  id: '/peer-reports',
  path: '/peer-reports',
  getParentRoute: () => AppRoute,
} as any)
const AppOracleRoute = AppOracleRouteImport.update({
  id: '/oracle',
  path: '/oracle',
  getParentRoute: () => AppRoute,
} as any)
const AppMyTasksRoute = AppMyTasksRouteImport.update({
  id: '/my-tasks',
  path: '/my-tasks',
  getParentRoute: () => AppRoute,
} as any)
const AppMessagesRoute = AppMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AppRoute,
} as any)
const AppMasterCalendarRoute = AppMasterCalendarRouteImport.update({
  id: '/master-calendar',
  path: '/master-calendar',
  getParentRoute: () => AppRoute,
} as any)
const AppLeaderboardRoute = AppLeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => AppRoute,
} as any)
const AppInboxRoute = AppInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => AppRoute,
} as any)
const AppFormsRoute = AppFormsRouteImport.update({
  id: '/forms',
  path: '/forms',
  getParentRoute: () => AppRoute,
} as any)
const AppFeedRoute = AppFeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => AppRoute,
} as any)
const AppDocsRoute = AppDocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppAttendanceRoute = AppAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsIndexRoute = AppProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => AppRoute,
} as any)
const AppTasksTaskIdRoute = AppTasksTaskIdRouteImport.update({
  id: '/tasks/$taskId',
  path: '/tasks/$taskId',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsProjectIdRoute = AppProjectsProjectIdRouteImport.update({
  id: '/projects/$projectId',
  path: '/projects/$projectId',
  getParentRoute: () => AppRoute,
} as any)
const AppFoldersFolderIdRoute = AppFoldersFolderIdRouteImport.update({
  id: '/folders/$folderId',
  path: '/folders/$folderId',
  getParentRoute: () => AppRoute,
} as any)
const AppDocsDocIdRoute = AppDocsDocIdRouteImport.update({
  id: '/$docId',
  path: '/$docId',
  getParentRoute: () => AppDocsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/phaethon': typeof PhaethonRoute
  '/register': typeof RegisterRoute
  '/admin': typeof AppAdminRoute
  '/attendance': typeof AppAttendanceRoute
  '/dashboard': typeof AppDashboardRoute
  '/docs': typeof AppDocsRouteWithChildren
  '/feed': typeof AppFeedRoute
  '/forms': typeof AppFormsRoute
  '/inbox': typeof AppInboxRoute
  '/leaderboard': typeof AppLeaderboardRoute
  '/master-calendar': typeof AppMasterCalendarRoute
  '/messages': typeof AppMessagesRoute
  '/my-tasks': typeof AppMyTasksRoute
  '/oracle': typeof AppOracleRoute
  '/peer-reports': typeof AppPeerReportsRoute
  '/reports': typeof AppReportsRoute
  '/room-booking': typeof AppRoomBookingRoute
  '/settings': typeof AppSettingsRoute
  '/social': typeof AppSocialRoute
  '/submissions': typeof AppSubmissionsRoute
  '/teams': typeof AppTeamsRoute
  '/f/$formId': typeof FFormIdRoute
  '/oauth/authorize': typeof OauthAuthorizeRoute
  '/docs/$docId': typeof AppDocsDocIdRoute
  '/folders/$folderId': typeof AppFoldersFolderIdRoute
  '/projects/$projectId': typeof AppProjectsProjectIdRoute
  '/tasks/$taskId': typeof AppTasksTaskIdRoute
  '/projects/': typeof AppProjectsIndexRoute
}
export interface FileRoutesByTo {
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/phaethon': typeof PhaethonRoute
  '/register': typeof RegisterRoute
  '/admin': typeof AppAdminRoute
  '/attendance': typeof AppAttendanceRoute
  '/dashboard': typeof AppDashboardRoute
  '/docs': typeof AppDocsRouteWithChildren
  '/feed': typeof AppFeedRoute
  '/forms': typeof AppFormsRoute
  '/inbox': typeof AppInboxRoute
  '/leaderboard': typeof AppLeaderboardRoute
  '/master-calendar': typeof AppMasterCalendarRoute
  '/messages': typeof AppMessagesRoute
  '/my-tasks': typeof AppMyTasksRoute
  '/oracle': typeof AppOracleRoute
  '/peer-reports': typeof AppPeerReportsRoute
  '/reports': typeof AppReportsRoute
  '/room-booking': typeof AppRoomBookingRoute
  '/settings': typeof AppSettingsRoute
  '/social': typeof AppSocialRoute
  '/submissions': typeof AppSubmissionsRoute
  '/teams': typeof AppTeamsRoute
  '/f/$formId': typeof FFormIdRoute
  '/oauth/authorize': typeof OauthAuthorizeRoute
  '/': typeof AppIndexRoute
  '/docs/$docId': typeof AppDocsDocIdRoute
  '/folders/$folderId': typeof AppFoldersFolderIdRoute
  '/projects/$projectId': typeof AppProjectsProjectIdRoute
  '/tasks/$taskId': typeof AppTasksTaskIdRoute
  '/projects': typeof AppProjectsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/phaethon': typeof PhaethonRoute
  '/register': typeof RegisterRoute
  '/_app/admin': typeof AppAdminRoute
  '/_app/attendance': typeof AppAttendanceRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/docs': typeof AppDocsRouteWithChildren
  '/_app/feed': typeof AppFeedRoute
  '/_app/forms': typeof AppFormsRoute
  '/_app/inbox': typeof AppInboxRoute
  '/_app/leaderboard': typeof AppLeaderboardRoute
  '/_app/master-calendar': typeof AppMasterCalendarRoute
  '/_app/messages': typeof AppMessagesRoute
  '/_app/my-tasks': typeof AppMyTasksRoute
  '/_app/oracle': typeof AppOracleRoute
  '/_app/peer-reports': typeof AppPeerReportsRoute
  '/_app/reports': typeof AppReportsRoute
  '/_app/room-booking': typeof AppRoomBookingRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/social': typeof AppSocialRoute
  '/_app/submissions': typeof AppSubmissionsRoute
  '/_app/teams': typeof AppTeamsRoute
  '/f/$formId': typeof FFormIdRoute
  '/oauth/authorize': typeof OauthAuthorizeRoute
  '/_app/': typeof AppIndexRoute
  '/_app/docs/$docId': typeof AppDocsDocIdRoute
  '/_app/folders/$folderId': typeof AppFoldersFolderIdRoute
  '/_app/projects/$projectId': typeof AppProjectsProjectIdRoute
  '/_app/tasks/$taskId': typeof AppTasksTaskIdRoute
  '/_app/projects/': typeof AppProjectsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/phaethon'
    | '/register'
    | '/admin'
    | '/attendance'
    | '/dashboard'
    | '/docs'
    | '/feed'
    | '/forms'
    | '/inbox'
    | '/leaderboard'
    | '/master-calendar'
    | '/messages'
    | '/my-tasks'
    | '/oracle'
    | '/peer-reports'
    | '/reports'
    | '/room-booking'
    | '/settings'
    | '/social'
    | '/submissions'
    | '/teams'
    | '/f/$formId'
    | '/oauth/authorize'
    | '/docs/$docId'
    | '/folders/$folderId'
    | '/projects/$projectId'
    | '/tasks/$taskId'
    | '/projects/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/forgot-password'
    | '/login'
    | '/phaethon'
    | '/register'
    | '/admin'
    | '/attendance'
    | '/dashboard'
    | '/docs'
    | '/feed'
    | '/forms'
    | '/inbox'
    | '/leaderboard'
    | '/master-calendar'
    | '/messages'
    | '/my-tasks'
    | '/oracle'
    | '/peer-reports'
    | '/reports'
    | '/room-booking'
    | '/settings'
    | '/social'
    | '/submissions'
    | '/teams'
    | '/f/$formId'
    | '/oauth/authorize'
    | '/'
    | '/docs/$docId'
    | '/folders/$folderId'
    | '/projects/$projectId'
    | '/tasks/$taskId'
    | '/projects'
  id:
    | '__root__'
    | '/_app'
    | '/forgot-password'
    | '/login'
    | '/phaethon'
    | '/register'
    | '/_app/admin'
    | '/_app/attendance'
    | '/_app/dashboard'
    | '/_app/docs'
    | '/_app/feed'
    | '/_app/forms'
    | '/_app/inbox'
    | '/_app/leaderboard'
    | '/_app/master-calendar'
    | '/_app/messages'
    | '/_app/my-tasks'
    | '/_app/oracle'
    | '/_app/peer-reports'
    | '/_app/reports'
    | '/_app/room-booking'
    | '/_app/settings'
    | '/_app/social'
    | '/_app/submissions'
    | '/_app/teams'
    | '/f/$formId'
    | '/oauth/authorize'
    | '/_app/'
    | '/_app/docs/$docId'
    | '/_app/folders/$folderId'
    | '/_app/projects/$projectId'
    | '/_app/tasks/$taskId'
    | '/_app/projects/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  PhaethonRoute: typeof PhaethonRoute
  RegisterRoute: typeof RegisterRoute
  FFormIdRoute: typeof FFormIdRoute
  OauthAuthorizeRoute: typeof OauthAuthorizeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/phaethon': {
      id: '/phaethon'
      path: '/phaethon'
      fullPath: '/phaethon'
      preLoaderRoute: typeof PhaethonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/oauth/authorize': {
      id: '/oauth/authorize'
      path: '/oauth/authorize'
      fullPath: '/oauth/authorize'
      preLoaderRoute: typeof OauthAuthorizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/f/$formId': {
      id: '/f/$formId'
      path: '/f/$formId'
      fullPath: '/f/$formId'
      preLoaderRoute: typeof FFormIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/teams': {
      id: '/_app/teams'
      path: '/teams'
      fullPath: '/teams'
      preLoaderRoute: typeof AppTeamsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/submissions': {
      id: '/_app/submissions'
      path: '/submissions'
      fullPath: '/submissions'
      preLoaderRoute: typeof AppSubmissionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/social': {
      id: '/_app/social'
      path: '/social'
      fullPath: '/social'
      preLoaderRoute: typeof AppSocialRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/room-booking': {
      id: '/_app/room-booking'
      path: '/room-booking'
      fullPath: '/room-booking'
      preLoaderRoute: typeof AppRoomBookingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports': {
      id: '/_app/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/peer-reports': {
      id: '/_app/peer-reports'
      path: '/peer-reports'
      fullPath: '/peer-reports'
      preLoaderRoute: typeof AppPeerReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/oracle': {
      id: '/_app/oracle'
      path: '/oracle'
      fullPath: '/oracle'
      preLoaderRoute: typeof AppOracleRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/my-tasks': {
      id: '/_app/my-tasks'
      path: '/my-tasks'
      fullPath: '/my-tasks'
      preLoaderRoute: typeof AppMyTasksRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/messages': {
      id: '/_app/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof AppMessagesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/master-calendar': {
      id: '/_app/master-calendar'
      path: '/master-calendar'
      fullPath: '/master-calendar'
      preLoaderRoute: typeof AppMasterCalendarRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/leaderboard': {
      id: '/_app/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof AppLeaderboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inbox': {
      id: '/_app/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof AppInboxRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/forms': {
      id: '/_app/forms'
      path: '/forms'
      fullPath: '/forms'
      preLoaderRoute: typeof AppFormsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/feed': {
      id: '/_app/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof AppFeedRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/docs': {
      id: '/_app/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof AppDocsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/attendance': {
      id: '/_app/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof AppAttendanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects/': {
      id: '/_app/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof AppProjectsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tasks/$taskId': {
      id: '/_app/tasks/$taskId'
      path: '/tasks/$taskId'
      fullPath: '/tasks/$taskId'
      preLoaderRoute: typeof AppTasksTaskIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects/$projectId': {
      id: '/_app/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof AppProjectsProjectIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/folders/$folderId': {
      id: '/_app/folders/$folderId'
      path: '/folders/$folderId'
      fullPath: '/folders/$folderId'
      preLoaderRoute: typeof AppFoldersFolderIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/docs/$docId': {
      id: '/_app/docs/$docId'
      path: '/$docId'
      fullPath: '/docs/$docId'
      preLoaderRoute: typeof AppDocsDocIdRouteImport
      parentRoute: typeof AppDocsRoute
    }
  }
}

interface AppDocsRouteChildren {
  AppDocsDocIdRoute: typeof AppDocsDocIdRoute
}

const AppDocsRouteChildren: AppDocsRouteChildren = {
  AppDocsDocIdRoute: AppDocsDocIdRoute,
}

const AppDocsRouteWithChildren =
  AppDocsRoute._addFileChildren(AppDocsRouteChildren)

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRoute
  AppAttendanceRoute: typeof AppAttendanceRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppDocsRoute: typeof AppDocsRouteWithChildren
  AppFeedRoute: typeof AppFeedRoute
  AppFormsRoute: typeof AppFormsRoute
  AppInboxRoute: typeof AppInboxRoute
  AppLeaderboardRoute: typeof AppLeaderboardRoute
  AppMasterCalendarRoute: typeof AppMasterCalendarRoute
  AppMessagesRoute: typeof AppMessagesRoute
  AppMyTasksRoute: typeof AppMyTasksRoute
  AppOracleRoute: typeof AppOracleRoute
  AppPeerReportsRoute: typeof AppPeerReportsRoute
  AppReportsRoute: typeof AppReportsRoute
  AppRoomBookingRoute: typeof AppRoomBookingRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppSocialRoute: typeof AppSocialRoute
  AppSubmissionsRoute: typeof AppSubmissionsRoute
  AppTeamsRoute: typeof AppTeamsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppFoldersFolderIdRoute: typeof AppFoldersFolderIdRoute
  AppProjectsProjectIdRoute: typeof AppProjectsProjectIdRoute
  AppTasksTaskIdRoute: typeof AppTasksTaskIdRoute
  AppProjectsIndexRoute: typeof AppProjectsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRoute,
  AppAttendanceRoute: AppAttendanceRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppDocsRoute: AppDocsRouteWithChildren,
  AppFeedRoute: AppFeedRoute,
  AppFormsRoute: AppFormsRoute,
  AppInboxRoute: AppInboxRoute,
  AppLeaderboardRoute: AppLeaderboardRoute,
  AppMasterCalendarRoute: AppMasterCalendarRoute,
  AppMessagesRoute: AppMessagesRoute,
  AppMyTasksRoute: AppMyTasksRoute,
  AppOracleRoute: AppOracleRoute,
  AppPeerReportsRoute: AppPeerReportsRoute,
  AppReportsRoute: AppReportsRoute,
  AppRoomBookingRoute: AppRoomBookingRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppSocialRoute: AppSocialRoute,
  AppSubmissionsRoute: AppSubmissionsRoute,
  AppTeamsRoute: AppTeamsRoute,
  AppIndexRoute: AppIndexRoute,
  AppFoldersFolderIdRoute: AppFoldersFolderIdRoute,
  AppProjectsProjectIdRoute: AppProjectsProjectIdRoute,
  AppTasksTaskIdRoute: AppTasksTaskIdRoute,
  AppProjectsIndexRoute: AppProjectsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  PhaethonRoute: PhaethonRoute,
  RegisterRoute: RegisterRoute,
  FFormIdRoute: FFormIdRoute,
  OauthAuthorizeRoute: OauthAuthorizeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
